project:
  type: book
  output-dir: _book
  render:
    - index.md
    - 01_schedule.md
    - 02_install_software.md
    - 03_update_software.md
    - 04_github_education.md

book:
  title: "DATA SCIENCE BOOTCAMP 2026"
  subtitle: "To do beforehand"
  output-file: bootcamp-prep
  repo-url: https://github.com/Data-Science-Bootcamp-2026/bootcamp-prep
  repo-actions:
    - issue
  downloads:
    - pdf
  page-navigation: true
  chapters:
    - index.md
    - 01_schedule.md
    - 02_install_software.md
    - 03_update_software.md
    - 04_github_education.md
  sidebar:
    title: "Bootcamp Prep"
    style: docked
    search: true

format:
  html:
    theme:
      light: litera
      dark: darkly
    css: styles.css
    number-sections: true
    toc: true
    toc-depth: 3
    page-layout: article
    link-external-newwindow: true
  pdf:
    documentclass: scrreprt
    number-sections: true
    toc: true
    geometry:
      - top=0.9in
      - bottom=0.9in
      - left=0.9in
      - right=0.9in
      - footskip=0.32in
