project:
  type: website
  output-dir: _site
  render:
    - 00_index.md
    - 01_schedule.md
    - 02_install_software.md
    - 03_update_software.md
    - 04_github_education.md

website:
  title: "Bootcamp Prep"
  repo-url: https://github.com/Data-Science-Bootcamp-2026/bootcamp-prep
  repo-actions:
    - issue
  page-navigation: true
  sidebar:
    title: "Bootcamp Prep"
    style: docked
    search: true
    tools:
      - icon: github
        href: https://github.com/Data-Science-Bootcamp-2026/bootcamp-prep
        aria-label: "Source code"
    contents:
      - text: "1 Welcome"
        href: 00_index.md
      - text: "2 Schedule"
        href: 01_schedule.md
      - text: "3 Install Software"
        href: 02_install_software.md
      - text: "4 (Optional) Update Software"
        href: 03_update_software.md
      - text: "5 (Optional) GitHub Education"
        href: 04_github_education.md

format:
  html:
    theme:
      light: litera
      dark: darkly
    css: styles.css
    toc: true
    toc-depth: 3
    page-layout: article
